# Site
repository: p-j-r.github.io
favicon: images/favicon.ico

# Content configuration version
version: 1

# Personal info
name: Paul Joseph Robin
title: #Senior Network System Administrator
email: pauljr1363@outlook.com
website: 

description: >- # this means to ignore newlines until the first ":"
  Bio

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username: p-j-r
instagram_username: __p.j.r
linkedin_username: pjr1363

# Google Analytics and Tag Manager
google_analytics: UA-161216424-1

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an undergraduate student in Physics at St. Stephen's College. I enjoy working through the mathematical aspects and exploring various theoretical models. I am comfortable programming in <mark>Python</mark>, <mark>C++</mark> and <mark>Fortran</mark>, and in learning new programming languages.
  
  Also familiar with the <mark>Qiskit</mark> and the <mark>PennyLane</mark> framework, I have an active interest in quantum computation and information. Particularly, my interest lies in the foundational details and its near-term impact on combating climate change and developing sustainable materials. 
  
  Check out this flash fiction [*The Frozen Galaxies*](https://shorts.quantumlah.org/entry/frozen-galaxies), submitted for the Quantum Shorts competition (other links towards the bottom of this page). 
  

# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects


# More Section
more_title: Other Interests
    #layout: text
more_content: | # this will include new lines to allow paragraphs
      Some other activities I enjoy:
      - Reading (With a soft spot for historical fiction)
      - Ocassionally writing poetry and stories Check these out: 
        - [*The Cat's Tale*](https://drive.google.com/file/d/1BrXcg-5VbFB12P2Y-WXuaUTrPJlLvQsP/view?usp=sharing), published in [Echo, the journal of Physics Society](https://drive.google.com/file/d/1OPJhxO70YS-j9N2r38UTQnFQRhtGo_eV/view))
        - [*The Frozen Galaxies*](https://shorts.quantumlah.org/entry/frozen-galaxies), submitted for the [Quantum Shorts](https://shorts.quantumlah.org/about) competition. 
      - Designing on Canva (Some of which end up with the poetry on [Instagram](https://www.instagram.com/__p.j.r/)).
      
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-feed
 - jekyll-seo-tag
